### ISSUE TITLE
What bar color patch?

### ISSUE THREAD

**Issue by ghost** [Fredins/gosu#1]
Hey, I'm thinking about adding a simple patch to the original gocaudices that supports this color system. What dwm patch is this change for?

Hope gocaudices has served you well btw :)

**Comment by fredins** [comment]
It is called status2d. Thanks for making gocaudices!

**Comment by ghost** [comment]
Hey I wanted to ask a an implementation question, since the patch seems to be able to do a lot more than just color. I was thinking of adding a `befstr` and `aftstf` strings to the `block` struct for status2d text before and after the output of `cmd`. Do you think this would be helpful and useable?

**Comment by fredins** [comment]
Yes that would be really nice. I would much prefer drawing icons using status2d instead of having to deal with icon fonts mess.

**Comment by ghost** [comment]
After playing around with it, it's definitely a very nice patch. [I think this is the exact functionality](https://github.com/LordRusk/gocaudices/tree/status2d) I'm looking for. However simple I'd love to hear if you think I could do something differently since I've only been playing with the patch for a few hours. Let me know :)
